services:
  api:
    image: ghcr.io/2025ca93027/fit_api
    container_name: fit_api
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      CONNECTIONSTRINGS__DEFAULT: Host=db;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      JWT__KEY: ${JWT__KEY}
      JWT__ISSUER: ${JWT__ISSUER}
      JWT__AUDIENCE: ${JWT__AUDIENCE}
    depends_on:
      db:
        condition: service_healthy

  migrate:
    image: ghcr.io/2025ca93027/fit_api_migrate
    container_name: fit_migrate
    restart: "no"
    environment:
      RUN_MIGRATIONS: "true"
      ASPNETCORE_ENVIRONMENT: Production
      CONNECTIONSTRINGS__DEFAULT: Host=db;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:18-alpine
    container_name: fit_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 10

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: fit_tunnel
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARED_TUNNEL_TOKEN}
    depends_on:
      - api
