<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>
    <PublishAot>true</PublishAot>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FIT.Core\FIT.Core.csproj" />
    <ProjectReference Include="..\FIT.Data\FIT.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Goals\" />
    <Folder Include="Progress\" />
    <Folder Include="Workouts\" />
  </ItemGroup>
  
</Project>
