@apiUrl = http://localhost:8080

###

GET {{apiUrl}}/goals
Accept: application/json

###

POST {{apiUrl}}/goals
Content-Type: application/json

{
    "name": "test goal",
    "targetValue": 15,
    "trackingMode": 2,
    "startDate": "2025-01-12"
}
